version: "3.7"
services:
  nginx:
    image: nginx:alpine
    working_dir: /app
    ports:
      - 80:80
    volumes:
      - ./:/app
      - ./nginx/conf.d:/etc/nginx/conf.d

  phpfpm:
    image: cyberduck/php-fpm-laravel:8.0
    working_dir: /app
    volumes:
      - ./:/app

  db:
    image: mysql
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  corsproxy:
    image: redocly/cors-anywhere
    ports:
        - 8080:8080
    environment:
        CORSANYWHERE_WHITELIST: http://videoquest.local/

volumes:
  dbdata:
